#default_dsn = sqlite://campteen.db
#default_dsn = mysql://ezpdo_ex:pdoiseasy@localhost/ezpdo_ex
#default_dsn = pgsql://ezpdo_ex:pdoiseasy@localhost/ezpdo_ex

dsn:
  development: mysql://root@localhost/campteen
  production: mysql://root@localhost/campteen

table:
  prefix: spmvc_